### create team
Post http://localhost:3000/team/create
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "name" : "title of New Project",
  "description" : "text ddddddddddddddssssddddddddddddddddddddddddssss",
  "username" : "My Team"
}
### get All Teams
GET  http://localhost:3000/team/list
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
### get one team By ID
GET  http://localhost:3000/team/651976db476da248338af316
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
### get Myteam  
GET  http://localhost:3000/team/me
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
### delete team By ID
DELETE  http://localhost:3000/team/remove/651976db476da248338af316
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
### invite user to team
GET  http://localhost:3000/team/invite/65196f74dacd2a9509b1aa82/AliNazari
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
### edit team By id
PUT   http://localhost:3000/team/update/65196f74dacd2a9509b1aa82
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
  "name" : "MostafaTeam" , 
  "description"  : "best developer team mosi" , 
  "tags" : ["",""]
}